syntax = "proto2";

import "store/common/common-proto.proto";
import "store/hotstuffstore/pbft-proto.proto";
import "store/hotstuffstore/server-proto.proto";

package hotstuffstore.proto;


// Sintr specific messages

message BeginValidateTxn {
  required uint64 client_id = 1;
  required uint64 client_seq_num = 2;
  required TxnState txn_state = 3;
  required TimestampMessage timestamp = 4;
}

message BeginValidateTxnMessage {
  oneof begin_one_of {
    BeginValidateTxn begin_validate_txn = 1;
    SignedMessage signed_begin_validate_txn = 2;
  }
}

message ForwardReadResult {
  optional uint64 client_id = 1;
  optional uint64 client_seq_num = 2;
  required bytes key = 3;
  required bytes value = 4;
  required TimestampMessage timestamp = 5;
}

message ForwardReadResultMessage {
  oneof forward_one_of {
    ForwardReadResult fwd_read_result = 1;
    SignedMessage signed_fwd_read_result = 2;
  }
  // server proof on read result
  optional CommitProof commit_proof = 3;
  optional SignedMessage server_read_sig = 4;
}

message FinishValidateTxnMessage {
  // client_id is the client that is sending this message
  required uint64 client_id = 1;
  // validation_txn_seq_num is the sequence number of the txn that was validated
  required uint64 validation_txn_seq_num = 2;
  oneof validation_one_of {
    bytes validation_txn_digest = 3;
    SignedMessage signed_validation_txn_digest = 4;
  }
  // optionally can compare entire transaction directly
  optional Transaction val_txn_msg = 5;
}